/**
 * catalog-lib.mjs — 单一真相源的加载、校验与代码发射。
 *
 * 真相源：src/catalog/catalog.json
 * 消费者：hub.html / scripts/probe-all.mjs / vite.config.ts / src/registry.ts / docs/*
 *
 * 设计要点：注入区用 CATALOG:BEGIN <label> / CATALOG:END <label> 包裹；首次运行时
 * 生成器自动定位既有区块并包裹标记（自举），之后每次只重写标记之间的内容。
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const catalogPath = path.join(root, 'src/catalog/catalog.json');

export const beginMark = (label) =>
  '/* CATALOG:BEGIN ' +
  label +
  ' — generated by node scripts/catalog-gen.mjs; edit src/catalog/catalog.json instead */';
export const endMark = (label) => '/* CATALOG:END ' + label + ' */';

export function loadCatalog() {
  return JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
}

/** 文件换行风格探测，生成内容与目标文件保持一致。 */
export function eolOf(src) {
  const crlf = (src.match(/\r\n/g) || []).length;
  const lf = (src.match(/\n/g) || []).length - crlf;
  return crlf > lf ? '\r\n' : '\n';
}

/**
 * 把 block 写入 openRe…closeRe 之间的区域，并加带标签的 CATALOG 标记。
 *
 * 幂等策略：先剥离已有的标记区（连同标记行），再按锚点重新插入 ——
 * 这样缩进、空行等排版每次都会被重算，不会累积脏格式。
 * 若源文件尚无锚点（新文件），则报错提示手工补锚点。
 */
export function replaceRegion(src, { label, openRe, closeRe, block, eol = '\n', indent = '' }) {
  let work = stripMarked(src, label);
  const om = openRe.exec(work);
  if (!om) throw new Error('[catalog] ' + label + ': 找不到起始锚点');
  const afterOpen = om.index + om[0].length;
  const tail = work.slice(afterOpen);
  const cm = closeRe.exec(tail);
  if (!cm) throw new Error('[catalog] ' + label + ': 找不到结束锚点');
  const closeAt = afterOpen + cm.index;
  const begin = indent + beginMark(label);
  const end = indent + endMark(label);
  return work.slice(0, afterOpen) + begin + eol + block + eol + end + work.slice(closeAt);
}

/**
 * 删除该标签的整个标记区：从 BEGIN 所在行的行首，到 END 标记文本结束为止。
 * 刻意**保留 END 之后的换行**，这样剥离后锚点区的收尾换行仍在，
 * 下一轮重新插入时能再次匹配到结束锚点（保证幂等）。
 */
function stripMarked(src, label) {
  const bi = src.indexOf(beginMark(label));
  if (bi === -1) return src;
  const ei = src.indexOf(endMark(label), bi);
  if (ei === -1) return src;
  const lineStart = src.lastIndexOf('\n', bi) + 1;
  return src.slice(0, lineStart) + src.slice(ei + endMark(label).length);
}

const BACKTICK = String.fromCharCode(96);
const q = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const tick = (s) => BACKTICK + s + BACKTICK;

/** hub.html 的 GENRES 字面量（只含 showcase !== false 的品类）。 */
export function emitGenres(genres, eol = '\n') {
  return genres
    .filter((g) => g.showcase !== false)
    .map((g) => {
      const spec = Object.entries(g.spec)
        .map(([k, v]) => k + ': ' + q(v))
        .join(', ');
      const blocks = g.blocks.map(([n, d]) => '[' + q(n) + ', ' + q(d) + ']').join(', ');
      return [
        '      {',
        '        id: ' + q(g.id) + ', icon: ' + q(g.icon) + ', title: ' + q(g.title) + ',',
        '        blurb: ' + q(g.blurb) + ',',
        '        tags: [' + g.tags.map(q).join(', ') + '],',
        '        demo: ' + q('./' + g.page + '.html') + ',',
        '        spec: { ' + spec + ' },',
        '        cmd: ' + q(g.cmd) + ',',
        '        createCmd: ' + q(g.createCmd) + ',',
        '        note: ' + q(g.note) + ',',
        '        blocks: [' + blocks + '],',
        '        thumb: ' + (g.thumb ? q(g.thumb) : 'null') + ',',
        '        status: ' + q(g.status) + ',',
        '      }',
      ].join(eol);
    })
    .join(',' + eol);
}

/** probe-all.mjs 的 pages 数组（含 hub）。 */
export function emitProbePages(genres, eol = '\n') {
  const rows = ["  ['hub', '/hub.html', 'hub'],"];
  for (const g of genres) {
    rows.push('  [' + q(g.id) + ', ' + q('/' + g.page + '.html') + ', ' + q(g.probe) + '],');
  }
  return rows.join(eol);
}

/** vite.config.ts 的多页 input。 */
export function emitViteInputs(genres, eol = '\n') {
  const rows = ["        main: 'index.html',", "        hub: 'hub.html',"];
  for (const g of genres) {
    rows.push('        ' + q(g.page) + ': ' + q(g.page + '.html') + ',');
  }
  return rows.join(eol);
}

/** registry.ts 的 GAME_LOADERS 条目。 */
export function emitLoaders(genres, eol = '\n') {
  return genres
    .map((g) => '  ' + propKey(g.gameId) + ': () => import(' + q(g.gameModule) + '),')
    .join(eol);
}

/** registry.ts 的 FILE_ALIASES（由 catalog 推导，含 index → 默认游戏）。 */
export function emitAliases(genres, eol = '\n') {
  const gameIds = new Set(genres.map((g) => g.gameId));
  const rows = ['  index: DEFAULT_GAME_ID,'];
  for (const g of genres) {
    // 页面名既不是注册键、也不等于注册键时，需要别名把文件名映射到内容包
    if (g.page !== g.gameId && !gameIds.has(g.page)) {
      rows.push('  ' + propKey(g.page) + ': ' + q(g.gameId) + ',');
    }
  }
  return rows.join(eol);
}

/** 对象字面量的键：合法标识符直接写，否则加引号（如 'fps-arena'）。 */
function propKey(k) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : q(k);
}

/** docs/CATALOG.md — 机器生成的参考清单。 */
export function emitCatalogDoc(cat, eol = '\n') {
  const L = [];
  L.push('# Catalog — 品类与配方总表（自动生成）');
  L.push('');
  L.push('> 本文件由 `node scripts/catalog-gen.mjs` 从 `src/catalog/catalog.json` 生成，**请勿手改**。');
  L.push('> 校验：`node scripts/catalog-check.mjs`（CI 强制零漂移）。updated: ' + cat.updated);
  L.push('');
  L.push('## 品类（' + cat.genres.length + '）');
  L.push('');
  L.push('| id | 页面 | 标题 | 状态 | 配方 | 探针 |');
  L.push('|---|---|---|---|---|---|');
  for (const g of cat.genres) {
    const recipe = g.recipe ? tick(g.recipe) : '—';
    L.push(
      '| ' + tick(g.id) + ' | [' + tick(g.page + '.html') + '](../' + g.page + '.html) | ' +
        g.icon + ' ' + g.title + ' | ' + g.status + ' | ' + recipe + ' | ' + tick(g.probe) + ' |',
    );
  }
  L.push('');
  L.push('## 配方（' + cat.recipes.length + '）');
  L.push('');
  L.push('| --recipe | 导出 | 文件 | 页面 |');
  L.push('|---|---|---|---|');
  for (const r of cat.recipes) {
    const page = r.page ? tick(r.page + '.html') : '—';
    L.push('| ' + tick(r.slug) + ' | ' + tick(r.export) + ' | ' + tick('src/recipes/' + r.file + '.ts') + ' | ' + page + ' |');
  }
  L.push('');
  L.push('## 新增一个品类的正确姿势');
  L.push('');
  L.push('1. 在 `src/catalog/catalog.json` 的 `genres` 里加一条（新配方还要加进 `recipes`）；');
  L.push('2. `node scripts/catalog-gen.mjs`（自动写 hub / probe / vite / registry / 本文档）；');
  L.push('3. `node scripts/catalog-check.mjs` 确认零漂移；');
  L.push('4. `npm run typecheck && npm test && npm run build && node scripts/probe-all.mjs`。');
  L.push('');
  return L.join(eol);
}

/** 校验 catalog 与实际仓库是否一致，返回问题列表。 */
export function validate(cat) {
  const problems = [];
  const { genres, recipes } = cat;
  const recipeSlugs = new Set(recipes.map((r) => r.slug));

  const seen = { id: new Set(), page: new Set(), gameId: new Set() };
  for (const g of genres) {
    for (const k of ['id', 'page', 'gameId']) {
      if (seen[k].has(g[k])) problems.push('重复 ' + k + ': ' + g[k]);
      seen[k].add(g[k]);
    }
    for (const f of ['icon', 'title', 'blurb', 'cmd', 'createCmd', 'note', 'probe', 'gameModule', 'status']) {
      if (!g[f]) problems.push(g.id + ': 缺字段 ' + f);
    }
    if (['playable', 'skeleton', 'template'].indexOf(g.status) === -1) {
      problems.push(g.id + ': status 非法 (' + g.status + ')');
    }
    // 页面文件必须存在
    if (!fs.existsSync(path.join(root, g.page + '.html'))) {
      problems.push(g.id + ': 页面不存在 ' + g.page + '.html');
    }
    // 内容包模块必须存在（支持 <name>.ts 与 <name>/index.ts 两种形态）
    const modBase = path.join(root, 'src', g.gameModule.replace(/^\.\//, ''));
    const modOk = fs.existsSync(modBase + '.ts') || fs.existsSync(path.join(modBase, 'index.ts'));
    if (!modOk) problems.push(g.id + ': 内容包不存在 ' + g.gameModule + '(.ts|/index.ts)');
    // 配方引用必须存在，且文件里确实导出了该工厂
    if (g.recipe != null) {
      if (!recipeSlugs.has(g.recipe)) problems.push(g.id + ': 引用了未知配方 ' + g.recipe);
      const r = recipes.find((x) => x.slug === g.recipe);
      if (r) checkRecipeFile(r, g.id, problems);
    }
    // 缩略图（生成后必须存在）
    if (g.thumb) {
      const t = path.join(root, 'public', g.thumb.replace(/^\.\//, ''));
      if (!fs.existsSync(t)) problems.push(g.id + ': 缩略图不存在 public/' + g.thumb.replace(/^\.\//, ''));
    }
  }

  for (const r of recipes) {
    for (const f of ['slug', 'export', 'file', 'title', 'blurb']) {
      if (!r[f]) problems.push('recipe ' + (r.slug || '?') + ': 缺字段 ' + f);
    }
    checkRecipeFile(r, null, problems);
    if (r.page) {
      const g = genres.find((x) => x.page === r.page);
      if (!g) problems.push('recipe ' + r.slug + ': 页面 ' + r.page + '.html 不在 genres 中');
      else if (g.recipe !== r.slug) {
        problems.push('recipe ' + r.slug + ': 与 ' + g.id + '.recipe(' + g.recipe + ') 不一致');
      }
    }
  }

  // 文档漂移：每个配方都要在 RECIPES.md 出现
  const recipesMd = path.join(root, 'docs/RECIPES.md');
  if (fs.existsSync(recipesMd)) {
    const md = fs.readFileSync(recipesMd, 'utf8');
    for (const r of recipes) {
      if (md.indexOf(tick(r.slug)) === -1) problems.push('docs/RECIPES.md 缺配方 ' + tick(r.slug));
    }
  } else {
    problems.push('docs/RECIPES.md 不存在');
  }

  return problems;
}

function checkRecipeFile(r, ownerId, problems) {
  const rf = path.join(root, 'src/recipes', r.file + '.ts');
  const who = ownerId ? ownerId + ': ' : 'recipe ' + r.slug + ': ';
  if (!fs.existsSync(rf)) {
    problems.push(who + '配方文件不存在 src/recipes/' + r.file + '.ts');
    return;
  }
  const src = fs.readFileSync(rf, 'utf8');
  if (!(new RegExp('export function ' + r.export + '\\b')).test(src)) {
    problems.push(who + 'src/recipes/' + r.file + '.ts 未导出 ' + r.export);
  }
}

/**
 * 生成目标清单 —— gen 与 check **共用**，保证「生成」与「校验」用同一套锚点与缩进。
 * full() 表示整文件生成；其余走 replaceRegion 注入。
 */
export function buildTargets(cat) {
  return [
    {
      label: 'hub-genres',
      file: 'hub.html',
      indent: '    ',
      openRe: /const GENRES = \[\r?\n/,
      closeRe: /\r?\n {4}\];/,
      block: (eol) => emitGenres(cat.genres, eol),
    },
    {
      label: 'probe-pages',
      file: 'scripts/probe-all.mjs',
      indent: '  ',
      openRe: /const pages = \[\r?\n/,
      closeRe: /\r?\n\];/,
      block: (eol) => emitProbePages(cat.genres, eol),
    },
    {
      label: 'vite-inputs',
      file: 'vite.config.ts',
      indent: '        ',
      openRe: /input: \{\r?\n/,
      closeRe: /\r?\n {6}\},/,
      block: (eol) => emitViteInputs(cat.genres, eol),
    },
    {
      label: 'registry-loaders',
      file: 'src/registry.ts',
      indent: '  ',
      openRe: /export const GAME_LOADERS: Record<string, GameLoader> = \{\r?\n/,
      closeRe: /\r?\n\};/,
      block: (eol) => emitLoaders(cat.genres, eol),
    },
    {
      label: 'registry-aliases',
      file: 'src/registry.ts',
      indent: '  ',
      openRe: /const FILE_ALIASES: Record<string, string> = \{\r?\n/,
      closeRe: /\r?\n\};/,
      block: (eol) => emitAliases(cat.genres, eol),
    },
    {
      label: 'docs-catalog',
      file: 'docs/CATALOG.md',
      full: (eol) => emitCatalogDoc(cat, eol) + '\n',
    },
  ];
}

export { q as quote };
