/**
 * Scaffold a new content package.
 *
 *   npm run new-game mygame
 *   npm run new-game mygame -- --title "My Game" --html
 *   npm run new-game mytd -- --recipe td --html
 *
 * Copies demo-template → src/game/<id>, rewrites id/title, registers in
 * src/registry.ts, and optionally adds <id>.html + vite multi-page input.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  if (i >= 0 && process.argv[i + 1]) return process.argv[i + 1];
  return fallback;
}

const id = process.argv[2];
if (!id || !/^[a-z][a-z0-9-]*$/.test(id)) {
  console.error('usage: node scripts/new-game.mjs <id> [--title "Title"] [--html]');
  process.exit(1);
}
const title = arg('title', id.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase()));
const wantHtml = process.argv.includes('--html');
const recipe = arg('recipe', 'blank'); // blank | td | survival | arpg | fps-arena | ... | survival | arpg | collect | rally | dungeon | flight-arena

const srcDir = path.join(root, 'src/game', id);
if (fs.existsSync(srcDir)) {
  console.error(`already exists: src/game/${id}`);
  process.exit(1);
}

fs.mkdirSync(srcDir, { recursive: true });

if (recipe === 'td') {
  const code = `/**
 * \`${id}\` — tower defense via recipe (edit the data below).
 * Generated by npm run new-game --recipe td
 */
import { towerDefenseRecipe } from '../../recipes/tower-defense';

export default towerDefenseRecipe({
  id: '${id}',
  title: '${title}',
  lane: [
    { x: -24, y: 0, z: 0 },
    { x: -10, y: 0, z: 5 },
    { x: 2, y: 0, z: -5 },
    { x: 14, y: 0, z: 3 },
    { x: 24, y: 0, z: 0 },
  ],
  pads: [
    { x: -6, z: 8 },
    { x: 4, z: -8 },
    { x: 12, z: 6 },
  ],
  startMoney: 120,
  baseHp: 20,
  // waves / towers: omit for defaults, or pass custom tables
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'arpg') {
  const code = `/**
 * \`${id}\` — top-down ARPG via recipe.
 */
import { arpgRecipe } from '../../recipes/arpg';

export default arpgRecipe({
  id: '${id}',
  title: '${title}',
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'survival') {
  const code = `/**
 * \`${id}\` — wave survival via recipe.
 * Generated by npm run new-game --recipe survival
 */
import { survivalRecipe } from '../../recipes/survival';

export default survivalRecipe({
  id: '${id}',
  title: '${title}',
  playerHp: 100,
  // waves: omit for defaults
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'collect') {
  const code = `import { collectRecipe } from '../../recipes/collect';

export default collectRecipe({
  id: '${id}',
  title: '${title}',
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'rally') {
  const code = `import { rallyRecipe } from '../../recipes/rally';

export default rallyRecipe({
  id: '${id}',
  title: '${title}',
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'dungeon') {
  const code = `import { dungeonRecipe } from '../../recipes/dungeon';

export default dungeonRecipe({
  id: '${id}',
  title: '${title}',
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'flight-arena') {
  const code = `import { flightArenaRecipe } from '../../recipes/flight-arena';

export default flightArenaRecipe({
  id: '${id}',
  title: '${title}',
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else if (recipe === 'fps-arena') {
  const code = `import { fpsArenaRecipe } from '../../recipes/fps-arena';

export default fpsArenaRecipe({
  id: '${id}',
  title: '${title}',
});
`;
  fs.writeFileSync(path.join(srcDir, 'index.ts'), code);
} else {
  const template = path.join(root, 'src/game/demo-template');
  fs.cpSync(template, srcDir, { recursive: true });
  const index = path.join(srcDir, 'index.ts');
  let code = fs.readFileSync(index, 'utf8');
  code = code
    .replace(/id: 'template'/g, `id: '${id}'`)
    .replace(/title: 'Template'/g, `title: '${title}'`)
    .replace(/createTemplateGame/g, `create${title.replace(/[^a-zA-Z0-9]/g, '')}Game`)
    .replace(/template\.present/g, `${id}.present`)
    .replace(/TemplateDeps/g, `${title.replace(/[^a-zA-Z0-9]/g, '')}Deps`)
    .replace(/game-template — empty content package skeleton\./, `Content package \`${id}\`.`);
  fs.writeFileSync(index, code);
}

// 3) register in src/registry.ts
const regPath = path.join(root, 'src/registry.ts');
let reg = fs.readFileSync(regPath, 'utf8');
const entry = `  ${id}: () => import('./game/${id}'),\n  // NEW_GAME_INSERT`;
if (reg.includes('// NEW_GAME_INSERT')) {
  reg = reg.replace('  // NEW_GAME_INSERT', entry);
  fs.writeFileSync(regPath, reg);
} else {
  console.warn('WARN: NEW_GAME_INSERT marker missing in registry.ts — add the import manually');
}

// 4) optional standalone HTML
if (wantHtml) {
  const html = `<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <meta name="theme-color" content="#0a0e16" />
    <link rel="icon" href="data:," />
    <link rel="stylesheet" href="./src/styles.css" />
    <script>window.__GAME_ID__ = '${id}';</script>
  </head>
  <body>
    <div id="app"></div>
    <div id="boot">
      <div class="bootLogo">${title}</div>
      <div class="bootSub">${id.toUpperCase()}</div>
      <div class="bootBarWrap"><div id="bootFill"></div></div>
      <div id="bootTxt">Loading…</div>
    </div>
    <script type="module" src="./src/main.ts"></script>
  </body>
</html>
`;
  fs.writeFileSync(path.join(root, `${id}.html`), html);

  const vitePath = path.join(root, 'vite.config.ts');
  let vite = fs.readFileSync(vitePath, 'utf8');
  if (vite.includes(`'${id}': '${id}.html'`)) {
    // already present
  } else if (vite.includes("arena: 'arena.html',")) {
    vite = vite.replace(
      "arena: 'arena.html',",
      `arena: 'arena.html',\n        ${id}: '${id}.html',`,
    );
    fs.writeFileSync(vitePath, vite);
  } else {
    console.warn('WARN: could not patch vite.config.ts input — add HTML entry manually');
  }
}

console.log(`created src/game/${id} (recipe=${recipe})`);
console.log(`  open  ${wantHtml ? `/${id}.html` : '(add HTML entry or copy a skeleton page)'}`);
console.log(`  edit  src/game/${id}/index.ts`);
