import { chromium } from "playwright";
const errors = [];
const b = await chromium.launch({ channel: "chrome" });
const page = await b.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", (e) => errors.push(String(e).slice(0, 200)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); });
await page.goto("http://localhost:4188/?game=tower", { waitUntil: "networkidle", timeout: 60000 });
await page.waitForTimeout(2500);
const hud = await page.evaluate(() => document.getElementById("tower-hud")?.textContent || "no-hud");
console.log("TOWER HUD:", hud);
console.log("TOWER ERRORS:", errors.length ? errors.slice(0,3).join("||") : "none");
await page.screenshot({ path: "shots/tower_sample.png" });
await page.goto("http://localhost:4188/?game=cultivation", { waitUntil: "networkidle", timeout: 60000 });
await page.waitForTimeout(2500);
const hud2 = await page.evaluate(() => document.getElementById("cultivation-hud")?.textContent || "no-hud");
console.log("CULT HUD:", hud2);
console.log("CULT ERRORS:", errors.length ? errors.slice(0,3).join("||") : "none");
await page.screenshot({ path: "shots/cultivation_sample.png" });
await b.close();
