import { chromium } from "playwright";
const errors = [];
const b = await chromium.launch({ channel: "chrome" });
const page = await b.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", (e) => errors.push(String(e).slice(0, 200)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); });
await page.goto("http://localhost:4188/?game=cultivation", { waitUntil: "networkidle", timeout: 60000 });
await page.waitForTimeout(4000);
const hud = await page.evaluate(() => document.getElementById("cultivation-hud")?.textContent || "no-hud");
await page.keyboard.press("3");
await page.waitForTimeout(800);
const hud2 = await page.evaluate(() => document.getElementById("cultivation-hud")?.textContent || "no-hud");
console.log("CULT1:", hud.replace(/\n/g, " | "));
console.log("CULT2:", hud2.replace(/\n/g, " | "));
console.log("ERRORS:", errors.length ? errors.slice(0,3).join("||") : "none");
await page.screenshot({ path: "shots/cultivation_sample.png" });
await b.close();
