/**
 * Composition root — static game registry.
 * This file MAY import content packages; engine/blocks/content must NOT.
 * Scaffold (`npm run new-game`) inserts a new line here.
 *
 * Entry is selected by HTML page (`window.__GAME_ID__` or filename),
 * not by query-string.
 */
import type { DefinedGame } from './content/defineGame';

export type GameLoader = () => Promise<{ default: DefinedGame }>;

export const DEFAULT_GAME_ID = 'nightraid';

export const GAME_LOADERS: Record<string, GameLoader> = {
  /* CATALOG:BEGIN registry-loaders — generated by node scripts/catalog-gen.mjs; edit src/catalog/catalog.json instead */
  nightraid: () => import('./game/nightraid/module'),
  fpsarena: () => import('./game/demo-fps-arena'),
  tower: () => import('./game/demo-tower'),
  cultivation: () => import('./game/demo-cultivation'),
  arpgdemo: () => import('./game/demo-arpg'),
  collectdemo: () => import('./game/demo-collect'),
  rallydemo: () => import('./game/demo-rally'),
  dungeondemo: () => import('./game/demo-dungeon'),
  flight: () => import('./game/demo-flight'),
  flightarena: () => import('./game/demo-flight-arena'),
  race: () => import('./game/demo-race'),
  tps: () => import('./game/demo-tps'),
  rogue: () => import('./game/demo-rogue'),
  plat: () => import('./game/demo-plat'),
  tycoon: () => import('./game/demo-tycoon'),
  rts: () => import('./game/demo-rts'),
  stealth: () => import('./game/demo-stealth'),
  arena: () => import('./game/demo-arena'),
  rhythm: () => import('./game/demo-rhythm'),
  sandbox: () => import('./game/demo-sandbox'),
  br: () => import('./game/demo-br'),
  puzzle: () => import('./game/demo-puzzle'),
  sports: () => import('./game/demo-sports'),
  template: () => import('./game/demo-template'),
  /* CATALOG:END registry-loaders */
};

/** HTML filename stem → registry id (when they differ). */
const FILE_ALIASES: Record<string, string> = {
  /* CATALOG:BEGIN registry-aliases — generated by node scripts/catalog-gen.mjs; edit src/catalog/catalog.json instead */
  index: DEFAULT_GAME_ID,
  fps: 'nightraid',
  'fps-arena': 'fpsarena',
  openworld: 'cultivation',
  arpg: 'arpgdemo',
  collect: 'collectdemo',
  rally: 'rallydemo',
  dungeon: 'dungeondemo',
  'flight-arena': 'flightarena',
  roguelike: 'rogue',
  platformer: 'plat',
  /* CATALOG:END registry-aliases */
};

export function resolveGameId(): string {
  const fromWindow = (globalThis as { __GAME_ID__?: string }).__GAME_ID__;
  if (fromWindow && fromWindow in GAME_LOADERS) return fromWindow;

  const base = (location.pathname.split('/').pop() || '').replace(/\.html$/i, '');
  if (base && base in FILE_ALIASES) return FILE_ALIASES[base];
  if (base && base in GAME_LOADERS) return base;

  return DEFAULT_GAME_ID;
}

export async function loadGame(id: string): Promise<DefinedGame> {
  const loader = GAME_LOADERS[id];
  if (!loader) {
    const known = listGameIds().join(', ');
    throw new Error(`[registry] unknown game id: "${id}". Known: ${known}`);
  }
  const mod = await loader();
  return mod.default;
}

export function listGameIds(): string[] {
  return Object.keys(GAME_LOADERS);
}
